# Generated by Django 4.2.9 on 2024-04-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('land_size', models.IntegerField()),
                ('crop_type', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('rainfall', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YieldPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_yield', models.FloatField()),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ifarmer.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='InputAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeds', models.IntegerField()),
                ('fertilizer', models.IntegerField()),
                ('pesticides', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifarmer.farmer')),
            ],
        ),
    ]
