# Generated by Django 4.2.9 on 2024-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifarmer', '0002_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=255)),
                ('coefficients', models.JSONField()),
                ('intercept', models.FloatField()),
            ],
        ),
    ]
