# Generated by Django 4.2.9 on 2024-04-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifarmer', '0002_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='seed_allocation',
            field=models.FloatField(default=0),
        ),
    ]
