# Generated by Django 4.2.9 on 2024-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifarmer', '0003_farmer_seed_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='output',
            field=models.FloatField(default=0),
        ),
    ]
